### ISSUE TITLE
你好，你的主板有电流声音吗

### ISSUE THREAD

**Issue by rxay** [KanLai/12490F-GIGABYTE-B660M-RX6600-EFI#1]
我的主板是技嘉 B660M Gaming，在 CPU 变频（比如放视频）时声音很大

**Comment by KanLai** [comment]
> 我的主板是技嘉 B660M Gaming，在 CPU 变频（比如放视频）时声音很大

有电流声，平常使用 也有

**Comment by rxay** [comment]
感觉这是技嘉主板的通病，我是放在桌子上用的，噪音比较吵，所以受不了。换了新主板，没声音了。
